# Generated by Django 4.0.8 on 2023-01-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
